### ISSUE TITLE
Tower generated for user coordinates

### ISSUE THREAD

**Issue by dhuan008** [Andymendez100/tower-finder#17]
![Capture](https://user-images.githubusercontent.com/33335681/59157192-4a9d7180-8a5b-11e9-9158-c7f6ae503a36.PNG)

**Comment by Andymendez100** [comment]
Pretty sure this bug is because of tom's data he sent us

**Comment by dhuan008** [comment]
Did you check his data? I think I tried looking up those coordinates they didn't show up are they in firebase?
