### ISSUE TITLE
Map and table display regardless of input

### ISSUE THREAD

**Issue by dhuan008** [Andymendez100/tower-finder#22]
I'm leaving it here so we don't forget to fix it.

**Comment by saynegrojas** [comment]
Ok i left an issue about this I think. I'll confirm with you first before I delete the issue I made.

**Comment by dhuan008** [comment]
For some reason I don't see it. Still getting used to GitHub. Feel free to delete this if you already documented it. I can't find issues 4-8

**Comment by Andymendez100** [comment]
I am able to fix the map and table not displaying but the loading button stays on screen

I am commenting on this so i remember later
