### ISSUE TITLE
Table row / info window "CITY" conflict

### ISSUE THREAD

**Issue by saynegrojas** [Andymendez100/tower-finder#24]
In the info window "city" information, it shows the correct different cities. Inside the table row "city" information, all of them say riverside.

**Comment by saynegrojas** [comment]
In the contentString var, I could just change it to "city" to match the table row information which is all Riverside, but when I put towerCity in the contentString, it's actually showing me the right cities.

**Comment by Andymendez100** [comment]
This has to do with the api that we are using to find the location of the cities

Tom's data has different boundaries compared to the api
